package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.37

import (
	"context"

	"github.com/Hinkku-Company/aphrodite_monolite/src/shared/graphql/generated"
	"github.com/Hinkku-Company/aphrodite_monolite/src/shared/models/schema"
)

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, input schema.Credentials) (*schema.Access, error) {
	return r.LoginModule.Login(ctx, input)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
