export ACCESS_TOKEN_PRIVATE_KEY=$(cat /app/ACCESS_TOKEN_PRIVATE_KEY.pem)
export ACCESS_TOKEN_PUBLIC_KEY=$(cat /app/ACCESS_TOKEN_PUBLIC_KEY.pem)
export REFRESH_TOKEN_PRIVATE_KEY=$(cat /app/REFRESH_TOKEN_PRIVATE_KEY.pem)
export REFRESH_TOKEN_PUBLIC_KEY=$(cat /app/REFRESH_TOKEN_PUBLIC_KEY.pem)